apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: explorage-ingress
  namespace: explorage
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  tls:
  rules:
    - host: explorage.local
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: explorage-backend-svc
              port:
                number: 8080
