apiVersion: v1
kind: Service
metadata:
  name: explorage-backend-svc
  namespace: explorage
spec:
  type: ClusterIP
  selector:
    app: explorage
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
